### ISSUE TITLE
Just got set up thanks! xDrip+ Doesn't get readings from .local (mDNS)

### ISSUE THREAD

**Issue by square-eyes** [jamorham/python-usb-wixel-xdrip#4]
I see data being collected in my Raspberry Pi console. I can also SSH from OSX to the Pi at raspberrypi.local but when I put raspberrypi.local:50005 in my receiver field on the android app, nothing happens.

I am using an xBridge also so I have selected "Wifi Wixel + xBridge Wixel" in my data source. When I'm close to the xDrip I get data. When I turn it off I get nothing from the RaspPi.

Any ideas?

**Comment by square-eyes** [comment]
Seems as though Android doesn't support mDNS, so .local addresses won't resolve from xDrip+. Unless I'm missing something raspberrypi.local as [shown in the tutorial](https://github.com/jamorham/python-usb-wixel-xdrip/blob/master/HOWTO.md) wouldn't work. I did however get it to work with he direct ip. Note you can ssh to .local addresses from OSX or a Win machine with Bonjour installed.

**Comment by square-eyes** [comment]
Not too sure if I'm missing something, but it would be great to enable this (I'm assuming it has to be done within xDrip+ [since Android doesn't support it natively](http://www.dodgycoder.net/2015/02/setting-up-bonjourzeroconfmdnsnsd.html)). Then I can grab a PI and take it to another network without trying to figure out its IP and inputting it in to the app.

**Comment by square-eyes** [comment]
This was fixed in a recent update to xDrip+ cheers!

**Comment by benhami1ton** [comment]
I'm having potentially a similar issue with xDrip+ connecting to my Pi. I can see that it's receiving data from the CGM transmitter (when using `sudo screen -r wixel` I get data coming in every 5 minutes pretty regularly)  In my case I don't have an xdrip bridge or anything except a single pi receiving data. Square-Eyes, when setting things up with a direct IP, was there anything else you had to do? I've tried each of the Wifi Wixel input configurations, and I've tried both local names and a direct IP. Any thoughts?

**Comment by old-square-eyes** [comment]
@benhami1ton are you on the latest xDrip+ nightly? I have been having problems (it was working well for some time), and am trying to investigate whether it's been broken.

**Comment by benhami1ton** [comment]
I think I'm just using the main version of xDrip+. Is there a separate apk for the nightly build version, or is it a setting within the app?

**Comment by old-square-eyes** [comment]
Will message you on Gitter.
